name: ml-ops.env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - azure-core==1.24.2
    - azure-storage-blob==12.13.0
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cryptography==37.0.4
    - flask==2.1.3
    - idna==3.3
    - importlib-metadata==4.12.0
    - isodate==0.6.1
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - markupsafe==2.1.1
    - msrest==0.7.1
    - oauthlib==3.2.0
    - pycparser==2.21
    - python-dotenv==0.20.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - six==1.16.0
    - typing-extensions==4.3.0
    - urllib3==1.26.10
    - werkzeug==2.1.2
    - zipp==3.8.1